name: Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Fetch dependencies
        run: yarn install --frozen-lockfile
      - name: Package binaries
        run: |
          yarn run build
          mv build polyglot-code-explorer
          cp README.md polyglot-code-explorer/
          cp CHANGELOG.md polyglot-code-explorer/
          mkdir dist
          zip dist/polyglot-code-explorer.zip polyglot-code-explorer
      - name: Release
        uses: docker://antonyurchenko/git-release:v3.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: 'false'
          PRE_RELEASE: 'false'
          CHANGELOG_FILE: 'CHANGELOG.md'
          ALLOW_EMPTY_CHANGELOG: 'false'
          ALLOW_TAG_PREFIX: 'true'
          RELEASE_NAME_PREFIX: 'Release: '
        with:
          args: |
            dist/*.zip
